import { describe, it, expect } from "vitest";

function encodePkKey(values: unknown[]): string {
  return JSON.stringify(values);
}

function decodePkKey(
  key: string,
  pkCols: { name: string }[]
): [string, unknown][] | null {
  let pkValues: unknown[];
  try {
    pkValues = JSON.parse(key) as unknown[];
  } catch {
    return null;
  }
  if (pkCols.length === 0 || pkValues.length !== pkCols.length) return null;
  return pkCols.map((c, i) => [c.name, pkValues[i]]);
}

function shouldSuppressKeyboard(
  editing: boolean,
  key: string,
  ctrlKey: boolean,
  metaKey: boolean
): boolean {
  if (!editing) {
    if (
      key === "Delete" ||
      key === "Backspace" ||
      key === "Enter" ||
      key === "F2" ||
      (key.length === 1 && !ctrlKey && !metaKey)
    ) {
      return true;
    }
  }
  return false;
}

function parseCellValue(raw: string, dataType: string): unknown {
  const t = dataType.toLowerCase();
  if (t.includes("int") || t === "serial" || t === "bigserial" || t === "smallserial") {
    const n = parseInt(raw.trim(), 10);
    return isNaN(n) ? raw : n;
  }
  if (t.includes("float") || t.includes("double") || t.includes("decimal") || t.includes("numeric") || t === "real") {
    const n = parseFloat(raw.trim());
    return isNaN(n) ? raw : n;
  }
  if (t === "boolean" || t === "bool") {
    return raw.trim().toLowerCase() === "true" || raw.trim() === "1";
  }
  return raw;
}

function generateTestValue(dataType: string, isPk: boolean, isAutoGenerated: boolean): unknown {
  const t = dataType.toLowerCase();
  if (isAutoGenerated || isPk) return null;
  if (t.includes("smallint") || t === "smallserial")
    return Math.floor(Math.random() * 30000);
  if (t.includes("int") || t === "serial" || t === "bigserial")
    return Math.floor(Math.random() * 10000);
  if (t.includes("float") || t.includes("double") || t.includes("numeric") || t.includes("decimal") || t === "real")
    return Math.round(Math.random() * 10000) / 100;
  if (t === "boolean" || t === "bool")
    return Math.random() > 0.5;
  if (t.includes("timestamp") || t === "timestamptz") {
    const d = new Date(Date.now() - Math.floor(Math.random() * 365 * 24 * 60 * 60 * 1000));
    return d.toISOString();
  }
  if (t === "date") {
    const d = new Date(Date.now() - Math.floor(Math.random() * 365 * 24 * 60 * 60 * 1000));
    return d.toISOString().split("T")[0];
  }
  if (t === "time") {
    const h = String(Math.floor(Math.random() * 24)).padStart(2, "0");
    const m = String(Math.floor(Math.random() * 60)).padStart(2, "0");
    const s = String(Math.floor(Math.random() * 60)).padStart(2, "0");
    return `${h}:${m}:${s}`;
  }
  if (t === "uuid") {
    return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, (c) => {
      const r = (Math.random() * 16) | 0;
      return (c === "x" ? r : (r & 0x3) | 0x8).toString(16);
    });
  }
  if (t === "json" || t === "jsonb")
    return JSON.stringify({ key: `value_${Math.floor(Math.random() * 100)}` });
  if (t.includes("char") || t === "text" || t.includes("varchar")) {
    const lenMatch = t.match(/\((\d+)\)/);
    const maxLen = lenMatch ? parseInt(lenMatch[1], 10) : 0;
    const words = ["ab", "cd", "hi", "go", "up", "ok", "ax", "do", "be", "my",
                    "alpha", "beta", "gamma", "delta", "test", "data", "item", "node", "key", "val"];
    if (maxLen > 0) {
      const candidates = words.filter((w) => w.length <= maxLen);
      if (candidates.length > 0) {
        const word = candidates[Math.floor(Math.random() * candidates.length)];
        const remaining = maxLen - word.length;
        if (remaining >= 2) {
          const numDigits = Math.min(remaining - 1, 4);
          const num = Math.floor(Math.random() * Math.pow(10, numDigits));
          return (word + "_" + num).slice(0, maxLen);
        }
        return word;
      }
      const chars = "abcdefghijklmnopqrstuvwxyz";
      let s = "";
      for (let i = 0; i < maxLen; i++) s += chars[Math.floor(Math.random() * chars.length)];
      return s;
    }
    return words[Math.floor(Math.random() * words.length)] + "_" + Math.floor(Math.random() * 1000);
  }
  return `test_${Math.floor(Math.random() * 1000)}`;
}

describe("DataGrid delete key encoding", () => {
  it("round-trips simple values", () => {
    const values = [1, "hello"];
    const key = encodePkKey(values);
    const pkCols = [{ name: "id" }, { name: "name" }];
    const decoded = decodePkKey(key, pkCols);
    expect(decoded).toEqual([
      ["id", 1],
      ["name", "hello"],
    ]);
  });

  it("round-trips values containing colon", () => {
    const values = ["a:b", "c:d:e"];
    const key = encodePkKey(values);
    const pkCols = [{ name: "x" }, { name: "y" }];
    const decoded = decodePkKey(key, pkCols);
    expect(decoded).toEqual([
      ["x", "a:b"],
      ["y", "c:d:e"],
    ]);
  });

  it("round-trips null and number", () => {
    const values = [null, 42];
    const key = encodePkKey(values);
    const decoded = decodePkKey(key, [{ name: "a" }, { name: "b" }]);
    expect(decoded).toEqual([
      ["a", null],
      ["b", 42],
    ]);
  });

  it("returns null for invalid JSON", () => {
    expect(decodePkKey("not json", [{ name: "id" }])).toBeNull();
  });

  it("returns null when key length does not match pk columns", () => {
    const key = encodePkKey([1]);
    expect(decodePkKey(key, [{ name: "id" }, { name: "id2" }])).toBeNull();
  });

  it("returns null for empty pk columns", () => {
    expect(decodePkKey("[1]", [])).toBeNull();
  });

  it("round-trips boolean and empty string", () => {
    const values = [true, "", false];
    const key = encodePkKey(values);
    const decoded = decodePkKey(key, [{ name: "a" }, { name: "b" }, { name: "c" }]);
    expect(decoded).toEqual([
      ["a", true],
      ["b", ""],
      ["c", false],
    ]);
  });
});

describe("DataGrid suppressKeyboardEvent", () => {
  describe("when not editing", () => {
    it("suppresses printable character keys", () => {
      expect(shouldSuppressKeyboard(false, "a", false, false)).toBe(true);
      expect(shouldSuppressKeyboard(false, "z", false, false)).toBe(true);
      expect(shouldSuppressKeyboard(false, "1", false, false)).toBe(true);
      expect(shouldSuppressKeyboard(false, " ", false, false)).toBe(true);
    });

    it("suppresses Delete key", () => {
      expect(shouldSuppressKeyboard(false, "Delete", false, false)).toBe(true);
    });

    it("suppresses Backspace key", () => {
      expect(shouldSuppressKeyboard(false, "Backspace", false, false)).toBe(true);
    });

    it("suppresses Enter key", () => {
      expect(shouldSuppressKeyboard(false, "Enter", false, false)).toBe(true);
    });

    it("suppresses F2 key", () => {
      expect(shouldSuppressKeyboard(false, "F2", false, false)).toBe(true);
    });

    it("does NOT suppress Ctrl+C (copy shortcut)", () => {
      expect(shouldSuppressKeyboard(false, "c", true, false)).toBe(false);
    });

    it("does NOT suppress Cmd+V (paste shortcut on Mac)", () => {
      expect(shouldSuppressKeyboard(false, "v", false, true)).toBe(false);
    });

    it("does NOT suppress Ctrl+A (select all)", () => {
      expect(shouldSuppressKeyboard(false, "a", true, false)).toBe(false);
    });

    it("does NOT suppress multi-character keys like Tab, Escape, Arrow", () => {
      expect(shouldSuppressKeyboard(false, "Tab", false, false)).toBe(false);
      expect(shouldSuppressKeyboard(false, "Escape", false, false)).toBe(false);
      expect(shouldSuppressKeyboard(false, "ArrowDown", false, false)).toBe(false);
      expect(shouldSuppressKeyboard(false, "ArrowUp", false, false)).toBe(false);
      expect(shouldSuppressKeyboard(false, "ArrowLeft", false, false)).toBe(false);
      expect(shouldSuppressKeyboard(false, "ArrowRight", false, false)).toBe(false);
    });

    it("does NOT suppress F1, F3-F12 (only F2 is suppressed)", () => {
      expect(shouldSuppressKeyboard(false, "F1", false, false)).toBe(false);
      expect(shouldSuppressKeyboard(false, "F3", false, false)).toBe(false);
      expect(shouldSuppressKeyboard(false, "F12", false, false)).toBe(false);
    });
  });

  describe("when already editing", () => {
    it("never suppresses any key", () => {
      expect(shouldSuppressKeyboard(true, "a", false, false)).toBe(false);
      expect(shouldSuppressKeyboard(true, "Delete", false, false)).toBe(false);
      expect(shouldSuppressKeyboard(true, "Backspace", false, false)).toBe(false);
      expect(shouldSuppressKeyboard(true, "Enter", false, false)).toBe(false);
      expect(shouldSuppressKeyboard(true, "F2", false, false)).toBe(false);
      expect(shouldSuppressKeyboard(true, " ", false, false)).toBe(false);
    });
  });
});

describe("parseCellValue", () => {
  describe("integer types", () => {
    it("parses valid integer", () => {
      expect(parseCellValue("42", "integer")).toBe(42);
      expect(parseCellValue(" 100 ", "bigint")).toBe(100);
      expect(parseCellValue("0", "smallint")).toBe(0);
      expect(parseCellValue("-5", "int")).toBe(-5);
    });

    it("parses serial types as integer", () => {
      expect(parseCellValue("1", "serial")).toBe(1);
      expect(parseCellValue("999", "bigserial")).toBe(999);
      expect(parseCellValue("7", "smallserial")).toBe(7);
    });

    it("returns raw string for non-numeric input", () => {
      expect(parseCellValue("abc", "integer")).toBe("abc");
      expect(parseCellValue("", "integer")).toBe("");
    });
  });

  describe("float types", () => {
    it("parses valid float", () => {
      expect(parseCellValue("3.14", "float")).toBe(3.14);
      expect(parseCellValue("100.5", "double precision")).toBe(100.5);
      expect(parseCellValue("99", "numeric")).toBe(99);
      expect(parseCellValue("0.001", "decimal")).toBe(0.001);
      expect(parseCellValue("2.5", "real")).toBe(2.5);
    });

    it("returns raw string for non-numeric input", () => {
      expect(parseCellValue("xyz", "float")).toBe("xyz");
    });
  });

  describe("boolean types", () => {
    it("parses true values", () => {
      expect(parseCellValue("true", "boolean")).toBe(true);
      expect(parseCellValue("TRUE", "bool")).toBe(true);
      expect(parseCellValue("1", "boolean")).toBe(true);
    });

    it("parses false values", () => {
      expect(parseCellValue("false", "boolean")).toBe(false);
      expect(parseCellValue("0", "bool")).toBe(false);
      expect(parseCellValue("anything", "boolean")).toBe(false);
    });
  });

  describe("string/other types", () => {
    it("returns raw string for text types", () => {
      expect(parseCellValue("hello", "text")).toBe("hello");
      expect(parseCellValue("world", "character varying")).toBe("world");
      expect(parseCellValue("test", "varchar(50)")).toBe("test");
    });

    it("returns raw string for unknown types", () => {
      expect(parseCellValue("data", "custom_type")).toBe("data");
    });
  });
});

describe("generateTestValue", () => {
  it("returns null for primary key columns", () => {
    expect(generateTestValue("integer", true, false)).toBeNull();
  });

  it("returns null for auto-generated columns", () => {
    expect(generateTestValue("integer", false, true)).toBeNull();
  });

  describe("integer types", () => {
    it("generates a number for integer", () => {
      const val = generateTestValue("integer", false, false);
      expect(typeof val).toBe("number");
      expect(Number.isInteger(val)).toBe(true);
    });

    it("generates smallint within range", () => {
      for (let i = 0; i < 20; i++) {
        const val = generateTestValue("smallint", false, false) as number;
        expect(val).toBeGreaterThanOrEqual(0);
        expect(val).toBeLessThan(30000);
      }
    });
  });

  describe("float types", () => {
    it("generates a number for numeric", () => {
      const val = generateTestValue("numeric", false, false);
      expect(typeof val).toBe("number");
    });

    it("generates a number for real", () => {
      const val = generateTestValue("real", false, false);
      expect(typeof val).toBe("number");
    });
  });

  describe("boolean", () => {
    it("generates a boolean", () => {
      const val = generateTestValue("boolean", false, false);
      expect(typeof val).toBe("boolean");
    });
  });

  describe("temporal types", () => {
    it("generates ISO timestamp", () => {
      const val = generateTestValue("timestamp", false, false) as string;
      expect(new Date(val).toISOString()).toBe(val);
    });

    it("generates date string (YYYY-MM-DD)", () => {
      const val = generateTestValue("date", false, false) as string;
      expect(val).toMatch(/^\d{4}-\d{2}-\d{2}$/);
    });

    it("generates time string (HH:MM:SS)", () => {
      const val = generateTestValue("time", false, false) as string;
      expect(val).toMatch(/^\d{2}:\d{2}:\d{2}$/);
    });
  });

  describe("uuid", () => {
    it("generates valid UUID v4 format", () => {
      const val = generateTestValue("uuid", false, false) as string;
      expect(val).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/);
    });
  });

  describe("json types", () => {
    it("generates valid JSON for json type", () => {
      const val = generateTestValue("json", false, false) as string;
      expect(() => JSON.parse(val)).not.toThrow();
    });

    it("generates valid JSON for jsonb type", () => {
      const val = generateTestValue("jsonb", false, false) as string;
      const parsed = JSON.parse(val);
      expect(parsed).toHaveProperty("key");
    });
  });

  describe("string types with length constraints", () => {
    it("respects varchar(5) max length", () => {
      for (let i = 0; i < 30; i++) {
        const val = generateTestValue("character varying(5)", false, false) as string;
        expect(val.length).toBeLessThanOrEqual(5);
        expect(val.length).toBeGreaterThan(0);
      }
    });

    it("respects varchar(2) max length", () => {
      for (let i = 0; i < 30; i++) {
        const val = generateTestValue("character varying(2)", false, false) as string;
        expect(val.length).toBeLessThanOrEqual(2);
        expect(val.length).toBeGreaterThan(0);
      }
    });

    it("respects varchar(1) max length", () => {
      for (let i = 0; i < 30; i++) {
        const val = generateTestValue("character varying(1)", false, false) as string;
        expect(val.length).toBe(1);
      }
    });

    it("generates longer strings for unconstrained text", () => {
      const val = generateTestValue("text", false, false) as string;
      expect(typeof val).toBe("string");
      expect(val.length).toBeGreaterThan(0);
    });

    it("generates string for varchar without length", () => {
      const val = generateTestValue("character varying", false, false) as string;
      expect(typeof val).toBe("string");
      expect(val.length).toBeGreaterThan(0);
    });
  });

  describe("fallback", () => {
    it("generates a test_ string for unknown types", () => {
      const val = generateTestValue("custom_type", false, false) as string;
      expect(val).toMatch(/^test_\d+$/);
    });
  });
});
