import { describe, it, expect } from "vitest";

function encodePkKey(values: unknown[]): string {
  return JSON.stringify(values);
}

function decodePkKey(
  key: string,
  pkCols: { name: string }[]
): [string, unknown][] | null {
  let pkValues: unknown[];
  try {
    pkValues = JSON.parse(key) as unknown[];
  } catch {
    return null;
  }
  if (pkCols.length === 0 || pkValues.length !== pkCols.length) return null;
  return pkCols.map((c, i) => [c.name, pkValues[i]]);
}

function shouldSuppressKeyboard(
  editing: boolean,
  key: string,
  ctrlKey: boolean,
  metaKey: boolean
): boolean {
  if (!editing) {
    if (
      key === "Delete" ||
      key === "Backspace" ||
      key === "Enter" ||
      key === "F2" ||
      (key.length === 1 && !ctrlKey && !metaKey)
    ) {
      return true;
    }
  }
  return false;
}

function parseCellValue(raw: string, dataType: string): unknown {
  const t = dataType.toLowerCase();
  if (t.includes("int") || t === "serial" || t === "bigserial" || t === "smallserial") {
    const n = parseInt(raw.trim(), 10);
    return isNaN(n) ? raw : n;
  }
  if (t.includes("float") || t.includes("double") || t.includes("decimal") || t.includes("numeric") || t === "real") {
    const n = parseFloat(raw.trim());
    return isNaN(n) ? raw : n;
  }
  if (t === "boolean" || t === "bool") {
    return raw.trim().toLowerCase() === "true" || raw.trim() === "1";
  }
  return raw;
}

function generateTestValue(dataType: string, isPk: boolean, isAutoGenerated: boolean): unknown {
  const t = dataType.toLowerCase();
  if (isAutoGenerated || isPk) return null;
  if (t.includes("smallint") || t === "smallserial")
    return Math.floor(Math.random() * 30000);
  if (t.includes("int") || t === "serial" || t === "bigserial")
    return Math.floor(Math.random() * 10000);
  if (t.includes("float") || t.includes("double") || t.includes("numeric") || t.includes("decimal") || t === "real")
    return Math.round(Math.random() * 10000) / 100;
  if (t === "boolean" || t === "bool")
    return Math.random() > 0.5;
  if (t.includes("timestamp") || t === "timestamptz") {
    const d = new Date(Date.now() - Math.floor(Math.random() * 365 * 24 * 60 * 60 * 1000));
    return d.toISOString();
  }
  if (t === "date") {
    const d = new Date(Date.now() - Math.floor(Math.random() * 365 * 24 * 60 * 60 * 1000));
    return d.toISOString().split("T")[0];
  }
  if (t === "time") {
    const h = String(Math.floor(Math.random() * 24)).padStart(2, "0");
    const m = String(Math.floor(Math.random() * 60)).padStart(2, "0");
    const s = String(Math.floor(Math.random() * 60)).padStart(2, "0");
    return `${h}:${m}:${s}`;
  }
  if (t === "uuid") {
    return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, (c) => {
      const r = (Math.random() * 16) | 0;
      return (c === "x" ? r : (r & 0x3) | 0x8).toString(16);
    });
  }
  if (t === "json" || t === "jsonb")
    return JSON.stringify({ key: `value_${Math.floor(Math.random() * 100)}` });
  if (t.includes("char") || t === "text" || t.includes("varchar")) {
    const lenMatch = t.match(/\((\d+)\)/);
    const maxLen = lenMatch ? parseInt(lenMatch[1], 10) : 0;
    const words = ["ab", "cd", "hi", "go", "up", "ok", "ax", "do", "be", "my",
                    "alpha", "beta", "gamma", "delta", "test", "data", "item", "node", "key", "val"];
    if (maxLen > 0) {
      const candidates = words.filter((w) => w.length <= maxLen);
      if (candidates.length > 0) {
        const word = candidates[Math.floor(Math.random() * candidates.length)];
        const remaining = maxLen - word.length;
        if (remaining >= 2) {
          const numDigits = Math.min(remaining - 1, 4);
          const num = Math.floor(Math.random() * Math.pow(10, numDigits));
          return (word + "_" + num).slice(0, maxLen);
        }
        return word;
      }
      const chars = "abcdefghijklmnopqrstuvwxyz";
      let s = "";
      for (let i = 0; i < maxLen; i++) s += chars[Math.floor(Math.random() * chars.length)];
      return s;
    }
    return words[Math.floor(Math.random() * words.length)] + "_" + Math.floor(Math.random() * 1000);
  }
  return `test_${Math.floor(Math.random() * 1000)}`;
}

// --- Search navigation logic (extracted from DataGrid component) ---

interface SearchMatch {
  rowIndex: number;
  colId: string;
}

function buildSearchMatches(
  searchQuery: string,
  editingRows: unknown[][],
  columns: { name: string }[] | undefined
): SearchMatch[] {
  if (!searchQuery || !columns) return [];
  const q = searchQuery.toLowerCase();
  const matches: SearchMatch[] = [];
  for (let r = 0; r < editingRows.length; r++) {
    for (let c = 0; c < editingRows[r].length; c++) {
      const val = editingRows[r][c];
      const str =
        val === null || val === undefined
          ? "null"
          : typeof val === "object"
            ? JSON.stringify(val)
            : String(val);
      if (str.toLowerCase().includes(q) && columns[c]) {
        matches.push({ rowIndex: r, colId: columns[c].name });
      }
    }
  }
  return matches;
}

function computeNextIdx(current: number, total: number): number {
  if (total === 0) return -1;
  return current + 1 >= total ? 0 : current + 1;
}

function computePrevIdx(current: number, total: number): number {
  if (total === 0) return -1;
  return current - 1 < 0 ? total - 1 : current - 1;
}

function isCellSearchMatch(
  searchQuery: string,
  cellValue: unknown
): boolean {
  if (!searchQuery) return false;
  const str =
    cellValue === null || cellValue === undefined
      ? "null"
      : typeof cellValue === "object"
        ? JSON.stringify(cellValue)
        : String(cellValue);
  return str.toLowerCase().includes(searchQuery.toLowerCase());
}

function isCellSearchCurrent(
  currentMatch: SearchMatch | null,
  rowIndex: number,
  colField: string | undefined
): boolean {
  if (!currentMatch) return false;
  return rowIndex === currentMatch.rowIndex && colField === currentMatch.colId;
}

function formatSearchCounter(matchIdx: number, matchCount: number): string {
  if (matchCount === 0) return "No results";
  return `${matchIdx + 1} / ${matchCount}`;
}

describe("DataGrid search match building", () => {
  const cols = [{ name: "id" }, { name: "name" }, { name: "email" }];

  it("returns empty array for empty query", () => {
    const rows = [[1, "Alice", "alice@test.com"]];
    expect(buildSearchMatches("", rows, cols)).toEqual([]);
  });

  it("returns empty array when columns is undefined", () => {
    const rows = [[1, "Alice", "alice@test.com"]];
    expect(buildSearchMatches("alice", rows, undefined)).toEqual([]);
  });

  it("returns empty array for no data rows", () => {
    expect(buildSearchMatches("test", [], cols)).toEqual([]);
  });

  it("finds single match", () => {
    const rows = [[1, "Alice", "bob@test.com"]];
    const matches = buildSearchMatches("Alice", rows, cols);
    expect(matches).toEqual([{ rowIndex: 0, colId: "name" }]);
  });

  it("finds matches across multiple columns", () => {
    const rows = [[1, "alice", "alice@test.com"]];
    const matches = buildSearchMatches("alice", rows, cols);
    expect(matches).toEqual([
      { rowIndex: 0, colId: "name" },
      { rowIndex: 0, colId: "email" },
    ]);
  });

  it("finds matches across multiple rows", () => {
    const rows = [
      [1, "Alice", "alice@test.com"],
      [2, "Bob", "bob@test.com"],
      [3, "Alicia", "alicia@test.com"],
    ];
    const matches = buildSearchMatches("ali", rows, cols);
    expect(matches).toEqual([
      { rowIndex: 0, colId: "name" },
      { rowIndex: 0, colId: "email" },
      { rowIndex: 2, colId: "name" },
      { rowIndex: 2, colId: "email" },
    ]);
  });

  it("is case-insensitive", () => {
    const rows = [[1, "Alice", "ALICE@TEST.COM"]];
    const matches = buildSearchMatches("alice", rows, cols);
    expect(matches.length).toBe(2);
  });

  it("matches null values when searching for 'null'", () => {
    const rows = [[1, null, "test@test.com"]];
    const matches = buildSearchMatches("null", rows, cols);
    expect(matches).toEqual([{ rowIndex: 0, colId: "name" }]);
  });

  it("matches numeric values as strings", () => {
    const rows = [[42, "test", "test@test.com"]];
    const matches = buildSearchMatches("42", rows, cols);
    expect(matches).toEqual([{ rowIndex: 0, colId: "id" }]);
  });

  it("matches object values via JSON.stringify", () => {
    const rows = [[1, { key: "value" }, "test"]];
    const matches = buildSearchMatches("value", rows, cols);
    expect(matches).toEqual([{ rowIndex: 0, colId: "name" }]);
  });

  it("matches undefined values as 'null'", () => {
    const rows = [[1, undefined, "test"]];
    const matches = buildSearchMatches("null", rows, cols);
    expect(matches).toEqual([{ rowIndex: 0, colId: "name" }]);
  });

  it("returns no matches when query does not exist in data", () => {
    const rows = [[1, "Alice", "alice@test.com"]];
    expect(buildSearchMatches("zzz", rows, cols)).toEqual([]);
  });

  it("handles partial matches", () => {
    const rows = [[1, "testing", "test@test.com"]];
    const matches = buildSearchMatches("test", rows, cols);
    expect(matches).toEqual([
      { rowIndex: 0, colId: "name" },
      { rowIndex: 0, colId: "email" },
    ]);
  });

  it("skips columns beyond the columns array length", () => {
    const shortCols = [{ name: "id" }];
    const rows = [[1, "Alice", "alice@test.com"]];
    const matches = buildSearchMatches("alice", rows, shortCols);
    expect(matches).toEqual([]);
  });
});

describe("DataGrid search navigation index", () => {
  describe("computeNextIdx", () => {
    it("returns -1 for empty matches", () => {
      expect(computeNextIdx(0, 0)).toBe(-1);
    });

    it("advances to next index", () => {
      expect(computeNextIdx(0, 5)).toBe(1);
      expect(computeNextIdx(2, 5)).toBe(3);
    });

    it("wraps around from last to first", () => {
      expect(computeNextIdx(4, 5)).toBe(0);
    });

    it("wraps correctly with single match", () => {
      expect(computeNextIdx(0, 1)).toBe(0);
    });
  });

  describe("computePrevIdx", () => {
    it("returns -1 for empty matches", () => {
      expect(computePrevIdx(0, 0)).toBe(-1);
    });

    it("goes to previous index", () => {
      expect(computePrevIdx(3, 5)).toBe(2);
      expect(computePrevIdx(1, 5)).toBe(0);
    });

    it("wraps around from first to last", () => {
      expect(computePrevIdx(0, 5)).toBe(4);
    });

    it("wraps correctly with single match", () => {
      expect(computePrevIdx(0, 1)).toBe(0);
    });
  });
});

describe("DataGrid cell search class rules", () => {
  describe("isCellSearchMatch", () => {
    it("returns false for empty query", () => {
      expect(isCellSearchMatch("", "anything")).toBe(false);
    });

    it("returns true for matching string value", () => {
      expect(isCellSearchMatch("hello", "Hello World")).toBe(true);
    });

    it("returns false for non-matching value", () => {
      expect(isCellSearchMatch("xyz", "Hello World")).toBe(false);
    });

    it("matches null value against 'null' query", () => {
      expect(isCellSearchMatch("null", null)).toBe(true);
    });

    it("matches undefined value against 'null' query", () => {
      expect(isCellSearchMatch("null", undefined)).toBe(true);
    });

    it("matches numeric value", () => {
      expect(isCellSearchMatch("42", 42)).toBe(true);
    });

    it("matches object value via JSON", () => {
      expect(isCellSearchMatch("key", { key: "val" })).toBe(true);
    });

    it("is case-insensitive", () => {
      expect(isCellSearchMatch("HELLO", "hello world")).toBe(true);
    });

    it("returns false for null query coerced as empty", () => {
      expect(isCellSearchMatch("", null)).toBe(false);
    });
  });

  describe("isCellSearchCurrent", () => {
    it("returns false when currentMatch is null", () => {
      expect(isCellSearchCurrent(null, 0, "name")).toBe(false);
    });

    it("returns true when row and column match", () => {
      const current = { rowIndex: 2, colId: "email" };
      expect(isCellSearchCurrent(current, 2, "email")).toBe(true);
    });

    it("returns false when row does not match", () => {
      const current = { rowIndex: 2, colId: "email" };
      expect(isCellSearchCurrent(current, 3, "email")).toBe(false);
    });

    it("returns false when column does not match", () => {
      const current = { rowIndex: 2, colId: "email" };
      expect(isCellSearchCurrent(current, 2, "name")).toBe(false);
    });

    it("returns false when colField is undefined", () => {
      const current = { rowIndex: 0, colId: "id" };
      expect(isCellSearchCurrent(current, 0, undefined)).toBe(false);
    });
  });
});

describe("DataGrid search counter display", () => {
  it("shows 'No results' for zero matches", () => {
    expect(formatSearchCounter(-1, 0)).toBe("No results");
  });

  it("shows '1 / 1' for single match", () => {
    expect(formatSearchCounter(0, 1)).toBe("1 / 1");
  });

  it("shows '1 / 5' for first of five matches", () => {
    expect(formatSearchCounter(0, 5)).toBe("1 / 5");
  });

  it("shows '3 / 10' for third of ten matches", () => {
    expect(formatSearchCounter(2, 10)).toBe("3 / 10");
  });

  it("shows '5 / 5' for last match", () => {
    expect(formatSearchCounter(4, 5)).toBe("5 / 5");
  });
});

describe("DataGrid delete key encoding", () => {
  it("round-trips simple values", () => {
    const values = [1, "hello"];
    const key = encodePkKey(values);
    const pkCols = [{ name: "id" }, { name: "name" }];
    const decoded = decodePkKey(key, pkCols);
    expect(decoded).toEqual([
      ["id", 1],
      ["name", "hello"],
    ]);
  });

  it("round-trips values containing colon", () => {
    const values = ["a:b", "c:d:e"];
    const key = encodePkKey(values);
    const pkCols = [{ name: "x" }, { name: "y" }];
    const decoded = decodePkKey(key, pkCols);
    expect(decoded).toEqual([
      ["x", "a:b"],
      ["y", "c:d:e"],
    ]);
  });

  it("round-trips null and number", () => {
    const values = [null, 42];
    const key = encodePkKey(values);
    const decoded = decodePkKey(key, [{ name: "a" }, { name: "b" }]);
    expect(decoded).toEqual([
      ["a", null],
      ["b", 42],
    ]);
  });

  it("returns null for invalid JSON", () => {
    expect(decodePkKey("not json", [{ name: "id" }])).toBeNull();
  });

  it("returns null when key length does not match pk columns", () => {
    const key = encodePkKey([1]);
    expect(decodePkKey(key, [{ name: "id" }, { name: "id2" }])).toBeNull();
  });

  it("returns null for empty pk columns", () => {
    expect(decodePkKey("[1]", [])).toBeNull();
  });

  it("round-trips boolean and empty string", () => {
    const values = [true, "", false];
    const key = encodePkKey(values);
    const decoded = decodePkKey(key, [{ name: "a" }, { name: "b" }, { name: "c" }]);
    expect(decoded).toEqual([
      ["a", true],
      ["b", ""],
      ["c", false],
    ]);
  });
});

describe("DataGrid suppressKeyboardEvent", () => {
  describe("when not editing", () => {
    it("suppresses printable character keys", () => {
      expect(shouldSuppressKeyboard(false, "a", false, false)).toBe(true);
      expect(shouldSuppressKeyboard(false, "z", false, false)).toBe(true);
      expect(shouldSuppressKeyboard(false, "1", false, false)).toBe(true);
      expect(shouldSuppressKeyboard(false, " ", false, false)).toBe(true);
    });

    it("suppresses Delete key", () => {
      expect(shouldSuppressKeyboard(false, "Delete", false, false)).toBe(true);
    });

    it("suppresses Backspace key", () => {
      expect(shouldSuppressKeyboard(false, "Backspace", false, false)).toBe(true);
    });

    it("suppresses Enter key", () => {
      expect(shouldSuppressKeyboard(false, "Enter", false, false)).toBe(true);
    });

    it("suppresses F2 key", () => {
      expect(shouldSuppressKeyboard(false, "F2", false, false)).toBe(true);
    });

    it("does NOT suppress Ctrl+C (copy shortcut)", () => {
      expect(shouldSuppressKeyboard(false, "c", true, false)).toBe(false);
    });

    it("does NOT suppress Cmd+V (paste shortcut on Mac)", () => {
      expect(shouldSuppressKeyboard(false, "v", false, true)).toBe(false);
    });

    it("does NOT suppress Ctrl+A (select all)", () => {
      expect(shouldSuppressKeyboard(false, "a", true, false)).toBe(false);
    });

    it("does NOT suppress multi-character keys like Tab, Escape, Arrow", () => {
      expect(shouldSuppressKeyboard(false, "Tab", false, false)).toBe(false);
      expect(shouldSuppressKeyboard(false, "Escape", false, false)).toBe(false);
      expect(shouldSuppressKeyboard(false, "ArrowDown", false, false)).toBe(false);
      expect(shouldSuppressKeyboard(false, "ArrowUp", false, false)).toBe(false);
      expect(shouldSuppressKeyboard(false, "ArrowLeft", false, false)).toBe(false);
      expect(shouldSuppressKeyboard(false, "ArrowRight", false, false)).toBe(false);
    });

    it("does NOT suppress F1, F3-F12 (only F2 is suppressed)", () => {
      expect(shouldSuppressKeyboard(false, "F1", false, false)).toBe(false);
      expect(shouldSuppressKeyboard(false, "F3", false, false)).toBe(false);
      expect(shouldSuppressKeyboard(false, "F12", false, false)).toBe(false);
    });
  });

  describe("when already editing", () => {
    it("never suppresses any key", () => {
      expect(shouldSuppressKeyboard(true, "a", false, false)).toBe(false);
      expect(shouldSuppressKeyboard(true, "Delete", false, false)).toBe(false);
      expect(shouldSuppressKeyboard(true, "Backspace", false, false)).toBe(false);
      expect(shouldSuppressKeyboard(true, "Enter", false, false)).toBe(false);
      expect(shouldSuppressKeyboard(true, "F2", false, false)).toBe(false);
      expect(shouldSuppressKeyboard(true, " ", false, false)).toBe(false);
    });
  });
});

describe("parseCellValue", () => {
  describe("integer types", () => {
    it("parses valid integer", () => {
      expect(parseCellValue("42", "integer")).toBe(42);
      expect(parseCellValue(" 100 ", "bigint")).toBe(100);
      expect(parseCellValue("0", "smallint")).toBe(0);
      expect(parseCellValue("-5", "int")).toBe(-5);
    });

    it("parses serial types as integer", () => {
      expect(parseCellValue("1", "serial")).toBe(1);
      expect(parseCellValue("999", "bigserial")).toBe(999);
      expect(parseCellValue("7", "smallserial")).toBe(7);
    });

    it("returns raw string for non-numeric input", () => {
      expect(parseCellValue("abc", "integer")).toBe("abc");
      expect(parseCellValue("", "integer")).toBe("");
    });
  });

  describe("float types", () => {
    it("parses valid float", () => {
      expect(parseCellValue("3.14", "float")).toBe(3.14);
      expect(parseCellValue("100.5", "double precision")).toBe(100.5);
      expect(parseCellValue("99", "numeric")).toBe(99);
      expect(parseCellValue("0.001", "decimal")).toBe(0.001);
      expect(parseCellValue("2.5", "real")).toBe(2.5);
    });

    it("returns raw string for non-numeric input", () => {
      expect(parseCellValue("xyz", "float")).toBe("xyz");
    });
  });

  describe("boolean types", () => {
    it("parses true values", () => {
      expect(parseCellValue("true", "boolean")).toBe(true);
      expect(parseCellValue("TRUE", "bool")).toBe(true);
      expect(parseCellValue("1", "boolean")).toBe(true);
    });

    it("parses false values", () => {
      expect(parseCellValue("false", "boolean")).toBe(false);
      expect(parseCellValue("0", "bool")).toBe(false);
      expect(parseCellValue("anything", "boolean")).toBe(false);
    });
  });

  describe("string/other types", () => {
    it("returns raw string for text types", () => {
      expect(parseCellValue("hello", "text")).toBe("hello");
      expect(parseCellValue("world", "character varying")).toBe("world");
      expect(parseCellValue("test", "varchar(50)")).toBe("test");
    });

    it("returns raw string for unknown types", () => {
      expect(parseCellValue("data", "custom_type")).toBe("data");
    });
  });
});

describe("generateTestValue", () => {
  it("returns null for primary key columns", () => {
    expect(generateTestValue("integer", true, false)).toBeNull();
  });

  it("returns null for auto-generated columns", () => {
    expect(generateTestValue("integer", false, true)).toBeNull();
  });

  describe("integer types", () => {
    it("generates a number for integer", () => {
      const val = generateTestValue("integer", false, false);
      expect(typeof val).toBe("number");
      expect(Number.isInteger(val)).toBe(true);
    });

    it("generates smallint within range", () => {
      for (let i = 0; i < 20; i++) {
        const val = generateTestValue("smallint", false, false) as number;
        expect(val).toBeGreaterThanOrEqual(0);
        expect(val).toBeLessThan(30000);
      }
    });
  });

  describe("float types", () => {
    it("generates a number for numeric", () => {
      const val = generateTestValue("numeric", false, false);
      expect(typeof val).toBe("number");
    });

    it("generates a number for real", () => {
      const val = generateTestValue("real", false, false);
      expect(typeof val).toBe("number");
    });
  });

  describe("boolean", () => {
    it("generates a boolean", () => {
      const val = generateTestValue("boolean", false, false);
      expect(typeof val).toBe("boolean");
    });
  });

  describe("temporal types", () => {
    it("generates ISO timestamp", () => {
      const val = generateTestValue("timestamp", false, false) as string;
      expect(new Date(val).toISOString()).toBe(val);
    });

    it("generates date string (YYYY-MM-DD)", () => {
      const val = generateTestValue("date", false, false) as string;
      expect(val).toMatch(/^\d{4}-\d{2}-\d{2}$/);
    });

    it("generates time string (HH:MM:SS)", () => {
      const val = generateTestValue("time", false, false) as string;
      expect(val).toMatch(/^\d{2}:\d{2}:\d{2}$/);
    });
  });

  describe("uuid", () => {
    it("generates valid UUID v4 format", () => {
      const val = generateTestValue("uuid", false, false) as string;
      expect(val).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/);
    });
  });

  describe("json types", () => {
    it("generates valid JSON for json type", () => {
      const val = generateTestValue("json", false, false) as string;
      expect(() => JSON.parse(val)).not.toThrow();
    });

    it("generates valid JSON for jsonb type", () => {
      const val = generateTestValue("jsonb", false, false) as string;
      const parsed = JSON.parse(val);
      expect(parsed).toHaveProperty("key");
    });
  });

  describe("string types with length constraints", () => {
    it("respects varchar(5) max length", () => {
      for (let i = 0; i < 30; i++) {
        const val = generateTestValue("character varying(5)", false, false) as string;
        expect(val.length).toBeLessThanOrEqual(5);
        expect(val.length).toBeGreaterThan(0);
      }
    });

    it("respects varchar(2) max length", () => {
      for (let i = 0; i < 30; i++) {
        const val = generateTestValue("character varying(2)", false, false) as string;
        expect(val.length).toBeLessThanOrEqual(2);
        expect(val.length).toBeGreaterThan(0);
      }
    });

    it("respects varchar(1) max length", () => {
      for (let i = 0; i < 30; i++) {
        const val = generateTestValue("character varying(1)", false, false) as string;
        expect(val.length).toBe(1);
      }
    });

    it("generates longer strings for unconstrained text", () => {
      const val = generateTestValue("text", false, false) as string;
      expect(typeof val).toBe("string");
      expect(val.length).toBeGreaterThan(0);
    });

    it("generates string for varchar without length", () => {
      const val = generateTestValue("character varying", false, false) as string;
      expect(typeof val).toBe("string");
      expect(val.length).toBeGreaterThan(0);
    });
  });

  describe("fallback", () => {
    it("generates a test_ string for unknown types", () => {
      const val = generateTestValue("custom_type", false, false) as string;
      expect(val).toMatch(/^test_\d+$/);
    });
  });
});

// --- Multi-row selection and bulk deletion logic ---

interface SelectionState {
  deletedKeys: Set<string>;
}

function computeBulkDelete(
  selectedPkKeys: Set<string>,
  currentState: SelectionState,
): SelectionState {
  const next: SelectionState = { deletedKeys: new Set(currentState.deletedKeys) };
  for (const pkKey of selectedPkKeys) {
    if (pkKey.startsWith("__")) continue;
    next.deletedKeys.add(pkKey);
  }
  return next;
}

function getRowClasses(
  isInserted: boolean,
  isDeleted: boolean,
  isDetailRow: boolean,
  isMultiSelected: boolean,
): string {
  const classes: string[] = [];
  if (isInserted) classes.push("row-inserted");
  if (isDeleted) classes.push("row-deleted");
  if (isDetailRow) classes.push("row-selected");
  if (isMultiSelected) classes.push("row-multi-selected");
  return classes.join(" ");
}

function shouldHandleKeyAsDelete(
  key: string,
  selectionSize: number,
  targetTag: string,
  isEditable: boolean,
): boolean {
  if (selectionSize === 0) return false;
  if (key !== "Delete" && key !== "Backspace") return false;
  if (targetTag === "INPUT" || targetTag === "TEXTAREA" || isEditable) return false;
  return true;
}

function shouldHandleKeyAsSelectAll(
  key: string,
  ctrlKey: boolean,
  metaKey: boolean,
  targetTag: string,
  isEditable: boolean,
): boolean {
  if (key.toLowerCase() !== "a") return false;
  if (!ctrlKey && !metaKey) return false;
  if (targetTag === "INPUT" || targetTag === "TEXTAREA" || isEditable) return false;
  return true;
}

function contextMenuDeleteLabel(
  selectedCount: number,
  clickedRowInSelection: boolean,
  clickedRowAlreadyDeleted: boolean,
): { label: string; isBulk: boolean } {
  if (selectedCount > 1 && clickedRowInSelection) {
    return { label: `Delete ${selectedCount} selected rows`, isBulk: true };
  }
  if (clickedRowAlreadyDeleted) {
    return { label: "Undo delete", isBulk: false };
  }
  return { label: "Delete row", isBulk: false };
}

function deleteButtonLabel(count: number): string {
  return `Delete ${count} row${count > 1 ? "s" : ""}`;
}

describe("Multi-row selection bulk delete (PK-based)", () => {
  it("marks selected PK keys as deleted", () => {
    const selected = new Set(['[1]', '[2]', '[3]']);
    const result = computeBulkDelete(selected, { deletedKeys: new Set() });
    expect(result.deletedKeys.size).toBe(3);
    expect(result.deletedKeys.has('[1]')).toBe(true);
    expect(result.deletedKeys.has('[2]')).toBe(true);
    expect(result.deletedKeys.has('[3]')).toBe(true);
  });

  it("skips inserted rows (keys starting with __)", () => {
    const selected = new Set(['[1]', '__ins_0', '__ins_1']);
    const result = computeBulkDelete(selected, { deletedKeys: new Set() });
    expect(result.deletedKeys.size).toBe(1);
    expect(result.deletedKeys.has('[1]')).toBe(true);
  });

  it("skips rows without PKs (keys starting with __nopk_)", () => {
    const selected = new Set(['__nopk_0', '__nopk_1']);
    const result = computeBulkDelete(selected, { deletedKeys: new Set() });
    expect(result.deletedKeys.size).toBe(0);
  });

  it("preserves previously deleted keys", () => {
    const existing = new Set(['[99]']);
    const selected = new Set(['[10]']);
    const result = computeBulkDelete(selected, { deletedKeys: existing });
    expect(result.deletedKeys.size).toBe(2);
    expect(result.deletedKeys.has('[99]')).toBe(true);
    expect(result.deletedKeys.has('[10]')).toBe(true);
  });

  it("handles empty selection", () => {
    const result = computeBulkDelete(new Set(), { deletedKeys: new Set() });
    expect(result.deletedKeys.size).toBe(0);
  });

  it("does not duplicate keys already in deletedKeys", () => {
    const existing = new Set(['[1]']);
    const selected = new Set(['[1]', '[2]']);
    const result = computeBulkDelete(selected, { deletedKeys: existing });
    expect(result.deletedKeys.size).toBe(2);
  });

  it("handles single row selection", () => {
    const selected = new Set(['[30]']);
    const result = computeBulkDelete(selected, { deletedKeys: new Set() });
    expect(result.deletedKeys.size).toBe(1);
    expect(result.deletedKeys.has('[30]')).toBe(true);
  });

  it("mixes real PK keys and inserted rows correctly", () => {
    const selected = new Set(['[1,"alice"]', '[2,"bob"]', '__ins_0', '__ins_1']);
    const result = computeBulkDelete(selected, { deletedKeys: new Set() });
    expect(result.deletedKeys.size).toBe(2);
    expect(result.deletedKeys.has('[1,"alice"]')).toBe(true);
    expect(result.deletedKeys.has('[2,"bob"]')).toBe(true);
  });
});

describe("Row class computation with multi-selection", () => {
  it("returns empty string for normal row", () => {
    expect(getRowClasses(false, false, false, false)).toBe("");
  });

  it("returns row-inserted for inserted row", () => {
    expect(getRowClasses(true, false, false, false)).toBe("row-inserted");
  });

  it("returns row-deleted for deleted row", () => {
    expect(getRowClasses(false, true, false, false)).toBe("row-deleted");
  });

  it("returns row-selected for detail-view row", () => {
    expect(getRowClasses(false, false, true, false)).toBe("row-selected");
  });

  it("returns row-multi-selected for multi-selected row", () => {
    expect(getRowClasses(false, false, false, true)).toBe("row-multi-selected");
  });

  it("combines multiple classes", () => {
    const classes = getRowClasses(false, true, false, true);
    expect(classes).toContain("row-deleted");
    expect(classes).toContain("row-multi-selected");
  });

  it("combines all classes", () => {
    const classes = getRowClasses(true, true, true, true);
    expect(classes).toBe("row-inserted row-deleted row-selected row-multi-selected");
  });
});

describe("Keyboard handler: delete selected rows", () => {
  it("returns true for Delete key with selection", () => {
    expect(shouldHandleKeyAsDelete("Delete", 3, "DIV", false)).toBe(true);
  });

  it("returns true for Backspace key with selection", () => {
    expect(shouldHandleKeyAsDelete("Backspace", 1, "DIV", false)).toBe(true);
  });

  it("returns false when no rows are selected", () => {
    expect(shouldHandleKeyAsDelete("Delete", 0, "DIV", false)).toBe(false);
  });

  it("returns false when key is not Delete or Backspace", () => {
    expect(shouldHandleKeyAsDelete("Enter", 5, "DIV", false)).toBe(false);
    expect(shouldHandleKeyAsDelete("a", 5, "DIV", false)).toBe(false);
  });

  it("returns false when target is an INPUT", () => {
    expect(shouldHandleKeyAsDelete("Delete", 3, "INPUT", false)).toBe(false);
  });

  it("returns false when target is a TEXTAREA", () => {
    expect(shouldHandleKeyAsDelete("Delete", 3, "TEXTAREA", false)).toBe(false);
  });

  it("returns false when target is contentEditable", () => {
    expect(shouldHandleKeyAsDelete("Delete", 3, "DIV", true)).toBe(false);
  });
});

describe("Keyboard handler: select all", () => {
  it("returns true for Ctrl+A on non-input element", () => {
    expect(shouldHandleKeyAsSelectAll("a", true, false, "DIV", false)).toBe(true);
  });

  it("returns true for Cmd+A on non-input element", () => {
    expect(shouldHandleKeyAsSelectAll("a", false, true, "DIV", false)).toBe(true);
  });

  it("returns true for Ctrl+A with uppercase key", () => {
    expect(shouldHandleKeyAsSelectAll("A", true, false, "DIV", false)).toBe(true);
  });

  it("returns false without modifier key", () => {
    expect(shouldHandleKeyAsSelectAll("a", false, false, "DIV", false)).toBe(false);
  });

  it("returns false for wrong key", () => {
    expect(shouldHandleKeyAsSelectAll("b", true, false, "DIV", false)).toBe(false);
  });

  it("returns false when target is INPUT", () => {
    expect(shouldHandleKeyAsSelectAll("a", true, false, "INPUT", false)).toBe(false);
  });

  it("returns false when target is TEXTAREA", () => {
    expect(shouldHandleKeyAsSelectAll("a", true, false, "TEXTAREA", false)).toBe(false);
  });

  it("returns false when target is contentEditable", () => {
    expect(shouldHandleKeyAsSelectAll("a", true, false, "DIV", true)).toBe(false);
  });
});

describe("Context menu delete label", () => {
  it("shows bulk delete when multiple rows selected and clicked row is in selection", () => {
    const { label, isBulk } = contextMenuDeleteLabel(5, true, false);
    expect(label).toBe("Delete 5 selected rows");
    expect(isBulk).toBe(true);
  });

  it("shows single delete when only 1 row selected", () => {
    const { label, isBulk } = contextMenuDeleteLabel(1, true, false);
    expect(label).toBe("Delete row");
    expect(isBulk).toBe(false);
  });

  it("shows single delete when clicked row is not in selection", () => {
    const { label, isBulk } = contextMenuDeleteLabel(3, false, false);
    expect(label).toBe("Delete row");
    expect(isBulk).toBe(false);
  });

  it("shows undo delete when row is already deleted", () => {
    const { label, isBulk } = contextMenuDeleteLabel(0, false, true);
    expect(label).toBe("Undo delete");
    expect(isBulk).toBe(false);
  });

  it("shows bulk delete even when clicked row is already deleted if in multi-selection", () => {
    const { label, isBulk } = contextMenuDeleteLabel(4, true, true);
    expect(label).toBe("Delete 4 selected rows");
    expect(isBulk).toBe(true);
  });
});

describe("Delete button label", () => {
  it("shows singular for 1 row", () => {
    expect(deleteButtonLabel(1)).toBe("Delete 1 row");
  });

  it("shows plural for multiple rows", () => {
    expect(deleteButtonLabel(5)).toBe("Delete 5 rows");
  });

  it("shows singular for 0 rows (button hidden in practice)", () => {
    expect(deleteButtonLabel(0)).toBe("Delete 0 row");
  });

  it("shows plural for large counts", () => {
    expect(deleteButtonLabel(100)).toBe("Delete 100 rows");
  });
});
