import React, { useState, useRef, useEffect } from "react";
import { ColumnInfo } from "../../lib/tauri";
import "./DataGrid.css";

interface Props {
  value: unknown;
  column: ColumnInfo;
  isModified: boolean;
  isInserted: boolean;
  searchQuery?: string;
  rowIdx: number;
  colIdx: number;
  onCellChange: (rowIdx: number, colIdx: number, newValue: unknown) => void;
}

export const EditableCell = React.memo(function EditableCell({
  value,
  column,
  isModified,
  isInserted,
  searchQuery,
  rowIdx,
  colIdx,
  onCellChange,
}: Props) {
  const [editing, setEditing] = useState(false);
  const [editValue, setEditValue] = useState("");
  const inputRef = useRef<HTMLInputElement>(null);

  const isNull = value === null || value === undefined;
  const displayValue = isNull ? "NULL" : String(value);

  const committedRef = useRef(false);

  const handleDoubleClick = () => {
    committedRef.current = false;
    setEditing(true);
    setEditValue(isNull ? "" : String(value));
  };

  const commitEdit = () => {
    if (committedRef.current) return;
    committedRef.current = true;
    setEditing(false);
    if (editValue === "" && column.is_nullable) {
      onCellChange(rowIdx, colIdx, null);
      return;
    }
    const parsed = parseValue(editValue, column.data_type);
    onCellChange(rowIdx, colIdx, parsed);
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "Enter") {
      commitEdit();
    } else if (e.key === "Escape") {
      committedRef.current = true;
      setEditing(false);
    } else if (e.key === "Tab") {
      e.preventDefault();
      commitEdit();
    }
  };

  useEffect(() => {
    if (editing && inputRef.current) {
      inputRef.current.focus();
      inputRef.current.select();
    }
  }, [editing]);

  const isSearchMatch = (() => {
    if (!searchQuery) return false;
    const q = searchQuery.toLowerCase();
    if (isNull) return "null".includes(q);
    const str = typeof value === "object" ? JSON.stringify(value) : String(value);
    return str.toLowerCase().includes(q);
  })();

  const highlightText = (text: string): React.ReactNode => {
    if (!searchQuery) return text;
    const q = searchQuery.toLowerCase();
    const idx = text.toLowerCase().indexOf(q);
    if (idx === -1) return text;
    return (
      <>
        {text.slice(0, idx)}
        <mark className="cell-search-highlight">{text.slice(idx, idx + searchQuery.length)}</mark>
        {text.slice(idx + searchQuery.length)}
      </>
    );
  };

  const isAutoOnInsert = isInserted && column.is_auto_generated && isNull;

  const cellClass = [
    "grid-cell",
    isNull && !isAutoOnInsert ? "cell-null" : "",
    isModified ? "cell-modified" : "",
    isInserted ? "cell-inserted" : "",
    editing ? "cell-editing" : "",
    isSearchMatch ? "cell-search-match" : "",
    isAutoOnInsert ? "cell-auto" : "",
  ]
    .filter(Boolean)
    .join(" ");

  if (isAutoOnInsert) {
    return (
      <td className={cellClass} title="Auto-generated by database">
        <span className="cell-value cell-auto-label">auto</span>
      </td>
    );
  }

  if (editing) {
    return (
      <td className={cellClass}>
        <input
          ref={inputRef}
          className="cell-input"
          value={editValue}
          onChange={(e) => setEditValue(e.target.value)}
          onBlur={commitEdit}
          onKeyDown={handleKeyDown}
        />
      </td>
    );
  }

  return (
    <td className={cellClass} onDoubleClick={handleDoubleClick}>
      <span className="cell-value">{isSearchMatch ? highlightText(displayValue) : displayValue}</span>
    </td>
  );
});

function parseValue(raw: string, dataType: string): unknown {
  const t = dataType.toLowerCase();
  if (
    t.includes("int") ||
    t === "serial" ||
    t === "bigserial" ||
    t === "smallserial"
  ) {
    const n = parseInt(raw, 10);
    return isNaN(n) ? raw : n;
  }
  if (
    t.includes("float") ||
    t.includes("double") ||
    t.includes("decimal") ||
    t.includes("numeric") ||
    t === "real"
  ) {
    const n = parseFloat(raw);
    return isNaN(n) ? raw : n;
  }
  if (t === "boolean" || t === "bool") {
    return raw.toLowerCase() === "true" || raw === "1";
  }
  return raw;
}
